### ISSUE TITLE
Cupertino Alerts on web have a strange artifact on the button

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#211]
## Acceptance Criteria
* Should render normally

<img width="518" alt="Screen Shot 2019-11-14 at 9 25 04 AM" src="https://user-images.githubusercontent.com/2364772/68839313-bfd33980-06c0-11ea-87c0-d143bf335f7b.png">

**Comment by guidezpl** [comment]
Filed https://github.com/flutter/flutter/issues/49877
