### ISSUE TITLE
Text field demo fixes (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#212]
## Acceptance Criteria
* Phone number should respect the max count
* Placeholder text for the "Life Story" field should not be cut off
* Salary postfix color should be purple

**Comment by guidezpl** [comment]
For the phone number, I can either set the maxLength and that's it, or set it but allow users to go over, which demonstrates the error state. ![Screenshot 2020-01-31 at 13 18 27](https://user-images.githubusercontent.com/6655696/73538798-3106cb00-442c-11ea-9180-57bb778e1acb.png)


For the placeholder text, I was only able to get it to get truncated with ellipsis at very narrow widths on both mobile and desktop. Can you clarify?

According to Material guidance, the textfield suffix should be grey.

**Comment by rami-a** [comment]
* I like what you propose for phone number, going to to error state.
* I just tested the placeholder again, and the behavior seems fine to me, so thats all good
* Ok we can leave the color as grey
