### ISSUE TITLE
Investigate settings icon rendering on web

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#223]
## Acceptance Criteria
* Icon should render the same as on mobile/mac

<img width="88" alt="Screen Shot 2019-11-14 at 9 38 01 AM" src="https://user-images.githubusercontent.com/2364772/68840187-7edc2480-06c2-11ea-9129-8c2124bed0cf.png">

**Comment by guidezpl** [comment]
Closing in favor of https://github.com/material-components/material-components-flutter-gallery/issues/528
