### ISSUE TITLE
Implement 2D Transformations Demo (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#237]
## Acceptance Criteria
* Take the demo from existing gallery

**Comment by guidezpl** [comment]
I'm not sure if there's a right place to put this one. It's not Material, Cupertino, etc..

**Comment by rami-a** [comment]
I think we can put it in `Reference Styles & Media`

**Comment by guidezpl** [comment]
I thought it was 'Reference Styles', not 'Reference, Styles' that makes more sense now! :)

**Comment by rami-a** [comment]
TBH we should probably rename this section. There's no media in it. Maybe it should be called `Reference & Styles`. Thoughts?

cc @willlarche

**Comment by guidezpl** [comment]
What should the documentation link be?

**Comment by rami-a** [comment]
Hmm I'd say if there's any particular widget that is being used throughout the demo (like `Transform` or something) link to that, otherwise I'd say have no link (though you'll need to add support for no links being provided)
