### ISSUE TITLE
Hide platform mechanics setting for non-iOS/android

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#250]

**Comment by guidezpl** [comment]
@willlarche Thoughts? macOS as a platform is in now, just waiting for it to get to stable before merging https://github.com/flutter/samples/pull/192

**Comment by willlarche** [comment]
Does Flutter Material have iOS-specific behavior on macOS?

**Comment by guidezpl** [comment]
Yes

**Comment by willlarche** [comment]
Then I think we can keep it for all platforms. People may want to even play with it on web.
