### ISSUE TITLE
[Performance] Add URLs for Each Page

### ISSUE THREAD

**Issue by pennzht** [material-components/material-components-flutter-gallery#289]
## Acceptance Criteria
* Each page (demo, study, …) has an URL.
* In a browser, navigating to a page shows the corresponding URL in the address bar.
* In a browser, typing an URL in the address bar navigates to corresponding page.
* Navigating within the app updates the URL without breaking the app.
* In a browser, clicking the back button returns to its previous page.

**Comment by willlarche** [comment]
Needs guidance from @ferhatb
