### ISSUE TITLE
Shrine: Make Cart overflow number display correctly in RTL in Web (2)

### ISSUE THREAD

**Issue by pennzht** [material-components/material-components-flutter-gallery#333]
## Issue
The overflow number is a number shown on the cart tray such as "+1" when the number of products is too large.
Currently, the overflow number is not displayed in full when

- Shrine is run in Web, and
- The text direction is RTL.

This issue **only** exists in RTL in Web, but exists for both mobile and desktop.

## Acceptance Criteria
* Shrine's cart overflow number displays correctly in RTL in Web.

## Screenshots
![shrine-cart-rtl-desktop](https://user-images.githubusercontent.com/23219899/69370211-ca339b80-0c9d-11ea-893d-764405d86095.png)
![shrine-cart-rtl-mobile](https://user-images.githubusercontent.com/23219899/69370214-cbfd5f00-0c9d-11ea-94b7-054ca87e91e4.png)

**Comment by pennzht** [comment]
@ferhatb This issue still exists. Any progress/thoughts yet?

**Comment by ferhatb** [comment]
/cc @mdebbar , if you modify expanding_bottom_sheet.dart line 420 with Directionaily(textDirection.rtl, child: Row(.... you can repro issue.

I see the text correctly and the paragraph shows the "+1" text at 15.17pixels but we are setting text width to 15px causing wrap with overflow:hidden it is disappearing. RTL itself works fine

**Comment by guidezpl** [comment]
Per Mariam on the tracking sheet, not in OKRs for this quarter

**Comment by mdebbar** [comment]
I have an issue on the Flutter side tracking this: https://github.com/flutter/flutter/issues/46019

When I looked at this back in December, I found that in some cases, the same text could have slightly different width in LTR vs RTL. And we always measure in LTR.
