### ISSUE TITLE
Focus/Hover/Pressed state for carousel card on Flutter web (0.5)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#341]
## Acceptance Criteria
* Carousel cards have a hover/focus/pressed states on web

**Comment by rami-a** [comment]
This is apparently fixed now, so we can verify it in the next sprint

**Comment by perclasson** [comment]
Can confirm that this is fixed.
![web_issues](https://user-images.githubusercontent.com/1770678/73072780-2ab9a180-3eb6-11ea-82d9-7374a2168b4a.gif)
