### ISSUE TITLE
[Performance] Settings locale list animation is choppy (3)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#346]
## Acceptance Criteria
* Expand/collapse animation for settings should be smooth
* Look into different ListView constructor that recycles items

migrated issue: https://github.com/flutter/gallery/issues/46

**Comment by guidezpl** [comment]
I attempted an alternate method of animating (without AnimatedBuilder) which suffered worst (on average) performance. I don't intend to work on this as I'm not sure what to do
