### ISSUE TITLE
Portrait to landscape causes crash on iPad (3)

### ISSUE THREAD

**Issue by guidezpl** [material-components/material-components-flutter-gallery#363]
## Acceptance Criteria
* App doesn't crash when switching to landscape mode on iPad

**Comment by rami-a** [comment]
@guidezpl I can't seem to reproduce it, do you have more concrete repro steps?

**Comment by guidezpl** [comment]
I'll try again when in MUC

**Comment by guidezpl** [comment]
No longer able to reproduce, closing
