### ISSUE TITLE
Add options to the tabs demo (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#367]
## Acceptance Criteria
* Copy the options from the old gallery tabs demo

**Comment by guidezpl** [comment]
Are the options here just scrolling/non-scrolling?

**Comment by rami-a** [comment]
I was originally thinking the options would be `text only, icons only, text+icons` but maybe you're right. Scrolling/non-scrolling might be a better demonstration. So let's do that
