### ISSUE TITLE
[shrine] [a11y] [ios] Crash when clicking clear cart

### ISSUE THREAD

**Issue by dnfield** [material-components/material-components-flutter-gallery#416]
Turn on voiceover

Add anything to the cart

Get to the cart screen and activate `Clear Cart`.

App crashes.

This is almost certain an upstream bug in the iOS a11y bridge.  I haven't had time to debug further and don't want to lose track, so filing here for now.

**Comment by rami-a** [comment]
I can't repro this either, closing it out
