### ISSUE TITLE
Tooltips not appearing in correct position (material app within material app)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#439]
## Acceptance Criteria
* Tooltips appear in correct position

This is a result of having a material app within a material app. A bug with flutter/flutter

**Comment by perclasson** [comment]
Now that we no longer have material app within material app, this ticket is fixed.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-21 at 11 35 30](https://user-images.githubusercontent.com/1770678/72797836-28e7a800-3c42-11ea-9215-f1690a363a9f.png)
