### ISSUE TITLE
Text not wrapping on Study cards on web (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#479]
See screenshot for difference between macOS and web. Might be a flutter web framework problem

## Acceptance Criteria
* Study text wraps

**macOS:**
<img width="1026" alt="Screen Shot 2019-12-09 at 4 11 33 PM" src="https://user-images.githubusercontent.com/2364772/70473338-d5106d80-1a9e-11ea-8fa8-afe1b484c254.png">

**web:**
<img width="907" alt="Screen Shot 2019-12-09 at 4 11 44 PM" src="https://user-images.githubusercontent.com/2364772/70473339-d5106d80-1a9e-11ea-8f76-2e6c7322dbb5.png">

**Comment by guidezpl** [comment]
Found a solution. Still, I tried to repro with a simple example to try and explain the different behavior on macOS and web but couldn't so 🤷‍♂️
