### ISSUE TITLE
Shrine - Opening cart with screen reader active should start at the top of the cart (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#486]
## Acceptance Criteria
* Screen reader begins at top of shopping cart screen when it is opened

**Comment by perclasson** [comment]
I will add OrdinalSortKeys but they do not always seem to be respected, see https://github.com/material-components/material-components-flutter-gallery/issues/390

**Comment by perclasson** [comment]
Closed with https://github.com/flutter/samples/pull/295
