### ISSUE TITLE
Bringing up the keyboard on iPad causes the app to change to mobile layout (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#501]
## Acceptance Criteria
* All screens stay in desktop layout even when keyboard is up on tablet

**Comment by rami-a** [comment]
I'm unable to reproduce this but if someone else can please update the ticket with repro steps

**Comment by perclasson** [comment]
I am also unable to reproduce this on any simulator, and a physical iPad and Android tablet. I'll close this ticket as fixed until we see this again.
