### ISSUE TITLE
Bottom button alignment

### ISSUE THREAD

**Issue by johnpryan** [material-components/material-components-flutter-gallery#507]
The alignment on the bottom buttons looks weird when hovered over or tapped:

<img width="762" alt="Screen Shot 2019-12-16 at 1 10 10 PM" src="https://user-images.githubusercontent.com/1145719/70931506-a0079c00-2005-11ea-9148-aef4e8d4ad83.png">

## Acceptance Criteria
* text is centered on bottom buttons

**Comment by rami-a** [comment]
Ah good catch, I originally change this to help with some alignment stuff when text is scaled up, but I think this is more important.
