### ISSUE TITLE
Use consistent organization (1)

### ISSUE THREAD

**Issue by guidezpl** [material-components/material-components-flutter-gallery#514]
To silence the following error, we should pick a consistent bundle identifier
`Ambiguous organization in existing files: {com.example, io.flutter.demo}. The --org command
line argument must be specified to recreate project.`

## Acceptance Criteria
* Same organization used for all files

**Comment by rami-a** [comment]
`io.flutter.demo` should be used, that matches what Play Store and App Store expect.
