### ISSUE TITLE
Add copy to clipboard to web (0.5)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#516]
A workaround until flutter adds support for this is to use dart:html

Here is a Dart library with an example showing how to copy text to the clipboard on the web.
https://github.com/andresaraujo/clippy/blob/master/lib/browser.dart
Example using it:
https://github.com/andresaraujo/clippy/blob/master/example/web/main.dart

**Comment by pennzht** [comment]
Appears to be fixed:
https://github.com/flutter/flutter/issues/46020
https://github.com/flutter/flutter/issues/46022

I'll re-implement this later.

**Comment by perclasson** [comment]
This is in master, and not stable. It works to copy the text but the future never completes on web as it does on ios.

I created the issue https://github.com/flutter/flutter/issues/49349 for that.
