### ISSUE TITLE
Android system back button when Shrine cart is expanded pops back to home instead of dismissing cart. (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#519]
## To Repro
* Open shrine demo
* Open shopping cart
* Invoke android system back button

## Acceptance Criteria
* Cart should dismiss instead

**Comment by perclasson** [comment]
This seems to be another case of `MaterialApp` within `MaterialApp` not working properly.

I will move up the existing `WillPopScope` to above the `MaterialApp` to make this work.
