### ISSUE TITLE
Update the CI to fail if you forget to run the code segment generator

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#520]
## Acceptance Criteria
* CI fails if the code segment generator shows a diff

**Comment by perclasson** [comment]
An idea for how we could do it:
1. We would reorganize the file structure to have all of the code within samples/gallery i.e. the codeviewer_cli is sharing the pubspec.yaml with the rest of the app.
2. We can write a 'meta test' for the gallery app where we run the `writeSegments` function with the `targetFilePath` to a temp function. Then we can compare the MD5 hash for both files to see if there is a difference (to simplify it a bit we could just compare the file size).

**Comment by rami-a** [comment]
This seems reasonable to me. Thanks for taking this on @perclasson
