### ISSUE TITLE
Cannot run app on beta channel because of dependencies issues

### ISSUE THREAD

**Issue by perclasson** [material-components/material-components-flutter-gallery#527]
In beta we cannot fetch the dependencies because of `flutter_localized_countries`. 

```
Because every version of flutter_localized_countries from git depends on intl ^0.16.0 and every version of flutter_localizations from sdk depends on intl 0.15.8, flutter_localized_countries from git is incompatible with flutter_localizations from sdk.
So, because gallery depends on both flutter_localizations any from sdk and flutter_localized_countries from git, version solving failed.
Running "flutter pub get" in gallery...
pub get failed (1)
```

Let's decide if actually care about it, and if so, fix our dependencies to work with the different flutter channels.

**Comment by guidezpl** [comment]
I didn't have an issue getting dependencies on the beta channel on https://github.com/flutter/samples/pull/256, can you checkout and try?

**Comment by perclasson** [comment]
Does not help for me, `flutter pub get` still errors out with the same message. Here is my `flutter doctor -v`:

```dart
[✓] Flutter (Channel beta, v1.9.1+hotfix.2, on Mac OS X 10.15.2 19C57, locale en-DE)
    • Flutter version 1.9.1+hotfix.2 at /Users/perc/development/flutter
    • Framework revision 2d2a1ffec9 (5 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

```

**Comment by guidezpl** [comment]
Ah you need to upgrade

Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2
    19C57, locale en-US)
    • Flutter version 1.13.6 at
      /Users/plg/development/flutter
    • Framework revision 659dc8129d (4 weeks ago),
      2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

**Comment by perclasson** [comment]
That works! Great, thanks @guidezpl.
