### ISSUE TITLE
[Performance] Add performance monitoring to Gallery on web

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#543]
From Yuqian Li: If it's easy to add the monitoring, I do think the data could be very useful for the Q2 overhaul. Have you ever tried https://firebase.google.com/docs/perf-mon ?

**Comment by collinjackson** [comment]
Here is the Flutter plugin that sends performance monitoring data to Firebase:

https://pub.dev/packages/firebase_performance

Let me know if you have any issues with it, I'd love feedback.
