### ISSUE TITLE
Re-think the breakpoints for desktop layout

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#544]
Several people have noticed the gallery does not run in desktop layout on their laptops. This is because our current logic is to check if the shortest side is less than 700 pixels.

We should rethink this logic so that desktop layout is used for most laptops.

**Comment by willlarche** [comment]
Check orientation, read width rather than shortest side.

Portait: 700
Landscape: 1000

**Comment by pennzht** [comment]
See https://material.io/design/layout/responsive-layout-grid.html#breakpoints
