### ISSUE TITLE
DefaultFocusTraversal has been replaced by FocusTraversalGroup

### ISSUE THREAD

**Issue by perclasson** [material-components/material-components-flutter-gallery#545]
Improvements to focus support has been done done, with the following PR merged into master: https://github.com/flutter/flutter/pull/49235

* We need to replace the deprecated DefaultFocusTraversal with FocusTraversalGroup.
* We can now improve the Focus support by making use of `FocusOrder `.

**Comment by willlarche** [comment]
Fixed in gallery-master branch
