### ISSUE TITLE
[Performance] Resizing Window is not smooth

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-flutter-gallery#549]
Resize from the bottom right or left hand corner of window
A black background appears before it is filled in with the purple card color
Notice that the cards/assets on the main page shift slow and janky, not smooth at all

migrated issue: https://github.com/flutter/gallery/issues/57

**Comment by guidezpl** [comment]
FYI https://github.com/flutter/flutter/issues/50814

**Comment by perclasson** [comment]
Closing this ticket, as there is a flutter/flutter issue as @guidezpl pointed out above.
