### ISSUE TITLE
[Performance] Dragging tab in Chrome responsiveness breaks

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-flutter-gallery#551]
Go to flutter gallery in a new tab on an existing chrome window
Drag the tab to create a new chrome window
Notice that it completely breaks the UI and takes more than a few seconds to readjust
This happens again when you drag the tab back into a different chrome window

**Comment by guidezpl** [comment]
Fixed by https://github.com/flutter/engine/pull/16822
