### ISSUE TITLE
[Performance] Rally numbers missing inside tab's content

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#553]
## To repro
* Initial load, clicked through all the tabs and the numbers were there for each except budget
* Then went back to the other tabs and the numbers were missing
* Went back to main page
* Opened rally again and now bills showed a number but the others didn't
* After a few click through tabs the bills number also disappeared

## Acceptance Criteria
* Numbers should not disappear

migrated issue: https://github.com/flutter/gallery/issues/63

**Comment by perclasson** [comment]
I cannot reproduce this. Anyone who sees this please let us know what flutter version you are running (flutter doctor -v), what browser, what browser version and what screen size you have.
