### ISSUE TITLE
[Performance] All Apps load very slowly initially

### ISSUE THREAD

**Issue by guidezpl** [material-components/material-components-flutter-gallery#556]
On all (Rally, shine, fortnightly etc) apps the initial load is janky
Second time loading is better but still a bit slow

**Comment by perclasson** [comment]
This will be related to https://github.com/material-components/material-components-flutter-gallery/issues/552 so I'm assigning myself to this.

**Comment by guidezpl** [comment]
Migrated to https://github.com/flutter/gallery/issues/50
