### ISSUE TITLE
Turn off letter spacing when running on the web

### ISSUE THREAD

**Issue by mariamhas** [material-components/material-components-flutter-gallery#557]
Currently the Gallery sample uses character spacing with ellipses. This is not support on the web and removing this when running on the web should make the app run faster. There is a property called [kisWeb](https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html) to determine if the app is compiled to run on web that could be potentially used.

**Comment by perclasson** [comment]
Related to https://github.com/flutter/flutter/issues/51234

**Comment by perclasson** [comment]
cc @mariamhas @ferhatb:
Do you have any more details on this? I am not finding an issue exactly related to this on flutter/flutter.

It seems as if letter spacing works fine (see [dartpad](https://dartpad.dartlang.org/7e7d284593a8c78a4089f8c4fa6ce629)). But do you mean there is a performance drop in using it? Also which one is it:
- letter spacing 
- text overflow with ellipses

**Comment by perclasson** [comment]
cc @mdebbar

**Comment by mdebbar** [comment]
There is a known performance regression when rendering paragraphs that have letter spacing > 0. I'll work on fixing this regression. In the meantime, if the performance is too bad because of it, you can set letter spacing to zero when `kIsWeb` is true. This isn't related to ellipsis.

**Comment by perclasson** [comment]
Thank you, that makes sense.
