### ISSUE TITLE
[Performance] Add flutter_gallery__transition_perf benchmarks of the new Flutter gallery app

### ISSUE THREAD

**Issue by clocksmith** [material-components/material-components-flutter-gallery#559]
https://github.com/flutter/samples/issues/309

**Comment by liyuqian** [comment]
As https://github.com/flutter/samples/issues/309 is closed, I guess that I shall follow this one. Please let me know if there's anything that I can help. I also wonder if there's a relationship between "Sprint 20" and Flutter milestones https://github.com/flutter/flutter/milestones ?

**Comment by guidezpl** [comment]
There's no relationship between the two

**Comment by guidezpl** [comment]
Migrated to https://github.com/flutter/gallery/issues/45
