### ISSUE TITLE
Crane - Improve Focus support

### ISSUE THREAD

**Issue by perclasson** [material-components/material-components-flutter-gallery#568]
## Acceptance Criteria
* You can only navigate the navigation at the top the first time, when you have reached the destinations it is not possible to go back to the top
* If you shift-tab the first thing you do as you enter the app, it should scroll down all the way to the bottom as a destination on the bottom now has focus. (this should probably be a flutter/flutter issue)

**Comment by guidezpl** [comment]
Migrated to https://github.com/flutter/gallery/issues/28
