### ISSUE TITLE
Build additional screens for Rally (8)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#90]
## Acceptance Criteria
- The graph view does not have a desktop design at the moment and can be adapted:
![Simulator Screen Shot - iPad Air (3rd generation) - 2019-11-05 at 11 59 40](https://user-images.githubusercontent.com/1770678/68202349-d80dcf00-ffc3-11e9-8aad-acfa736564db.png)

Same with the Due and Budgets screens:
![due](https://user-images.githubusercontent.com/1770678/68202407-f83d8e00-ffc3-11e9-86dd-9183ea78024c.png)
![budgets](https://user-images.githubusercontent.com/1770678/68202408-f83d8e00-ffc3-11e9-97dc-063a6f4b8d01.png)

**Comment by perclasson** [comment]
I asked the oncall designer for opinions on how it should look like for now. So I'll hold this off until I get a response.
